### ISSUE TITLE
Support `bevy 0.12`

### ISSUE THREAD

**Issue by ActuallyHappening** [lifescapegame/bevy_replicon#110]
This is an awesome crate, and believe it or not is actually blocking me from upgrading to `bevy 0.12` :(
I'll try to do a simple upgrade, anything I should know about @Shatur?

**Comment by Shatur** [comment]
To upgrade this crate to bevy 0.12, I need Renet to be upgraded to 0.12 first.

**Comment by ActuallyHappening** [comment]
Oh yeah good point, I'll see what I can do

**Comment by solnyszczko** [comment]
https://github.com/lucaspoffo/renet/issues/124

renet supports .12 on main, and will have a proper release soon
