### ISSUE TITLE
Event ordering

### ISSUE THREAD

**Issue by UkoeHB** [lifescapegame/bevy_replicon#12]
The server event `sending_system` and the client event `receiving_system` are both configured in set `OnUpdate(ServerState::Hosting)`. This means a server response to a client event received by the server in tick A cannot be sent out until tick B (the same is true for a client responding to a server event). The default sending/receiving systems have private visibility too, meaning they can't be configured to run at other times.

Possible alternative:
- add `ServerSet::ReceiveEvent` and `ServerSet::SendEvent`
- use `.run_if(in_state(ServerState::Hosting))` for server endpoints, and `.run_if(in_state(ClientState::Connected))` for client endpoints

What do you think? This way the server sets can be configured.

**Comment by Shatur** [comment]
> The server event sending_system and the client event receiving_system are both configured in set OnUpdate(ServerState::Hosting). This means a server response to a client event received by the server in tick A cannot be sent out until tick B (the same is true for a client responding to a server event).

Systems that are in set `ServerState::Hosting` are not affected by the tick. But `sending_system` also inside `ServerSet::Tick`, so you are right: "server response to a client event received by the server in tick A cannot be sent out until tick B". I did this to avoid receiving events without the updated state.
Do you want to configure this behavior? What behavior would you like?

**Comment by Shatur** [comment]
Makes sense!
I think that `ServerSet::ReceiveEvent` and `ServerSet::SendEvent` should be good.

**Comment by Shatur** [comment]
Do you want me to draft a new release now or you have plans for other suggestions?

**Comment by Shatur** [comment]
Sure, no problem.

Curious, are you writing a library or a game?

**Comment by Shatur** [comment]
I assume you working on prediction + rollback?
Nice, let me know if you need anything from my side.
