### ISSUE TITLE
Rooms

### ISSUE THREAD

**Issue by Shatur** [lifescapegame/bevy_replicon#15]
Sometimes you replicate only part of the world. Commonly used for things like fog of war or card games.
To solve this `@koe` from Bevy discord server suggested to implement rooms.
Assign each entity a room ID (inspired by naia's rooms). Each client is a member of an arbitrary number of rooms (e.g. using a hashset of ids). By default entities are in room ‘0’ which means global (or maybe have no room IDs). All other room ids are user-defined. Replicon just needs a resource to track client room membership, and some updates to the replication logic to only replicate an entity for a given client if they are in the same room (and also to ‘despawn’ an entity if it stops being visible to a client).

**Comment by Shatur** [comment]
Yeah, this is exactly what `@koe` suggested.

**Comment by ActuallyHappening** [comment]
I would prefer a more flexible, sole server approach, where a function taking mutable world access, the player id and a specific entity returns a bool whether to replicate to client or not.

This way I can encode "chunking" (like minecraft does it, I presume) however I want to.

From my perspective, not having contributed to `bevy_replicon` much, this seems the easiest way from the consumers of this library's POV to not replicate the entire world.

This is a slow implementation, but I think configuring a function (signature) to decide which entities are replicated is the most powerful, flexible and easiest to integrate approach

**Comment by ActuallyHappening** [comment]
Yeah you're right, its more ECS friendly.
My use case would involve a room for each player, and every `FixedUpdate` frame updating each entity to be in all the rooms of players suitably nearby. Thus, you would need a data structure flexible enough for one room per player, and able to handle every frame many entities (on the server side) changing rooms.

Can't wait until this is finalised!

**Comment by Shatur** [comment]
Working on rooms right now.

In the proposed solution, we essentially assign an ID (room) to each object, and then specify which IDs each client sees.
But what if we use an existing entity ID (`Entity`) and just store it for each client? This approach have the same amount of flexibility,  much easier implement (users only modify entities that each client sees, entity IDs remain the same unlike with entity room) and faster due to keeping small `Replication` and less amount of lookups. To make it more convenient to use we should also have a policy switch (all entities, blacklist and whitelist). I will try to prototype it first and see how it goes.

**Comment by Shatur** [comment]
I wouldn't say "way more", but I agree that for some games it would be less convenient.
However the approach I mentioned is faster. It's even zero-cost when you don't use visibility! If it's too barebones for some games, users can easily extend it.
And it's also easy to implement. I played with it this morning and really how the API turned out. Maybe I will finish it quickly, show it and we will discuss?

**Comment by Shatur** [comment]
> We should make sure the 'how to extend it' story is figured out before releasing this.

Agree, consider it's a quick prototype.

> And add examples/tests for the various scenarios:

I want to showcase the working design first.
I will sure add test for any possible case when we agree on the design. I like tests, we have quite a high test coverage for a reason :)

**Comment by Shatur** [comment]
Let's move discussion about possible rooms API on top from the PR here.
You said:
```
 think it can be done with one custom SystemParam (instead of an entity component) called RepliconRooms with this core API:

    rooms.join(client id, room id)
    rooms.leave(client id, room id)
    rooms.add_entity(entity, room id)
    rooms.remove_entity(entity, room id)

I'm not sure how to integrate it with events. Maybe a bespoke solution is required (a distinct events API that wraps bevy_replicon, like RoomWriter or some such).
```

I think that a `SystemParam` is a way to go.
Alternatively it could be a `Room` component and a `ClientRooms` resource.

About events. How about to provide an extension trait for `App` that registers a room-based event (like `App::add_room_server_event`) and under the hood registers an event like `ToClients<RoomEvent<T>>` (with an alias to something like `ToRooms<T>`) with custom sending and receiving systems?
