### ISSUE TITLE
ServerState/ClientState conflict with disabling plugins

### ISSUE THREAD

**Issue by UkoeHB** [lifescapegame/bevy_replicon#18]
The methods `add_server_event_with()` and `add_client_event_with()` depend on both `ServerState` and `ClientState`. This means if you disable the server or client plugins then the program will crash on update with error 'resource not found' for the missing state.

The doc test demoing plugin disabling doesn't actually try to update the app. Here is an updated test that fails:

```rust
# use bevy::prelude::*;
# use bevy_replicon::prelude::*;
# let mut app = App::new();
app.add_plugins(MinimalPlugins).add_plugins(
    ReplicationPlugins
        .build()
        .disable::<ClientPlugin>()
        .set(ServerPlugin { tick_policy: TickPolicy::MaxTickRate(60) }),
);

# #[derive(Debug)]
# struct X;
# app.add_server_event_with::<X, _, _>(||{}, ||{});
# app.update();
```

**Comment by Shatur** [comment]
That's an problem... Possible solutions:
1. Detect if client or server plugins are enabled by checking `State<ClientState>` and `State<ServerState>` resources.
2. Add an enum option to event plugins that disables or enables client or server dependencies.
3. Split plugins into parts, one for server and one for client.

I personally think that the first one is the best.
