### ISSUE TITLE
Event cleaning guarantees?

### ISSUE THREAD

**Issue by uvizhe** [lifescapegame/bevy_replicon#29]
Hi,
I'm using your wonderful plugin in my game and so far almost everything was perfect.
However, today I noticed that my `on_client_event` condition fires my system twice (two consecutive frames) and on the second run in the system I get empty event reader.
The only two possible reasons I can think of for this strange behavior is either:
1) I do not read properly and the event queue doesn't clean until the next frame where I try to read from it but too late. I use `client_event.iter().next().unwrap()` to read an event.
2) After being read in the first invocation event queue does not clean on time, so on the next frame my condition fires again, and when my system runs the queue is already clean.

So the question is: can I expect `ClientEvent` to be empty after being read at the beginning of the next frame? And also am I right that network events are cleaned totally the same way as bevy events?

**Comment by Shatur** [comment]
It works exactly like regular events in Bevy: all events last two frames, but if you read them via `EventReader`, it remembers the events that were read, so the reader will be empty on the next frame.
But on client `ClientEvent` will be consumed to fired it locally, see https://github.com/lifescapegame/bevy_replicon/blob/cec608d1916be83802a400ec9faff2241fb59b86/src/network_event/client_event.rs#L279
The same thing about `ServerEvent` on server.
