### ISSUE TITLE
Running at higher FPS than MaxTickRate drops events?

### ISSUE THREAD

**Issue by Pierre-Borges** [lifescapegame/bevy_replicon#30]
I'm running at 60 FPS but the default MaxTickRate is ony 30. This seems to cause server events to be dropped. I think the problem is that the events are only around for one Update cycle but the server system that requests them only runs half of the time.
I tried removing the in_set condition on the sending_system and that fixed it. I think that it was fixed because the system now runs on every Update cycle.

**Comment by Pierre-Borges** [comment]
It is also fixed if I make the MaxTickRate 60 but that takes way more bandwidth I think?

**Comment by Shatur** [comment]
Oh, right, It's a bug, I should switch to manual event cleanup.

> It is also fixed if I make the MaxTickRate 60 but that takes way more bandwidth I think?

If your world changes more often - yes.

**Comment by Shatur** [comment]
Could you try #31?

**Comment by Pierre-Borges** [comment]
That works, yes!

**Comment by Shatur** [comment]
Great, I will draft a new release this evening.
