### ISSUE TITLE
Optimize world diff consumption

### ISSUE THREAD

**Issue by UkoeHB** [lifescapegame/bevy_replicon#33]
### Problem

Clients deserialize world diffs into a pile of allocated bits (vectors and map nodes).

### Solution

Use a span or similar byte magic to access serialized world diffs directly.

**Comment by Shatur** [comment]
Alternatively we could apply world diff using https://github.com/bevyengine/bevy/pull/6421

**Comment by Shatur** [comment]
Closed by #39, we apply world diff directly.
